server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    username: ${takeout.datasource.username}
    password: ${takeout.datasource.password}
    url: ${takeout.datasource.url}
    driver-class-name: ${takeout.datasource.driver-class-name}


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #驼峰命名映射 idNUmber -> id_number

# https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  helper-dialect: 'mariadb'
  offset-as-page-num: true
  page-size-zero: true
logging:
  level:
    com:
      takeout:
        mapper: debug
        service: info
# https://cloud.tencent.com/document/product/436
tencent-cloud-cos:
  region: ${tencent-cloud-cos.region}
  secret-id: ${tencent-cloud-cos.secret-id}
  secret-key: ${tencent-cloud-cos.secret-key}
  bucket-name: ${tencent-cloud-cos.bucket-name}
  storage: ${tencent-cloud-cos.storage-path}