takeout:
  datasource:
    url: jdbc:mariadb://localhost:3306/takeout?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: Tomatos
    password: 20030503
token:
  expiration: 86400 # 1天
  prefix: 'token'
  secret-key: 'your-very-secure-jwt-secret-key-2024!@#ABCdef1234567890'